#############################################################################
# Makefile for building: bin/Lattice_Boltzmann
# Generated by qmake (1.07a) (Qt 3.3.7) on: Sat Feb 16 16:17:23 2008
# Project:  qtRipp.pro
# Template: app
# Command: $(QMAKE) -o Makefile qtRipp.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
CXXFLAGS = -pipe -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/share/qt3/mkspecs/default -I. -I. -Isrc -I/usr/include/vtk-5.0 -I/usr/include/qt3
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L/usr/share/qt3/lib -L/usr/X11R6/lib -lvtkWidgets -lvtkFiltering -lvtkImaging -lvtkHybrid -lvtkGraphics -lQVTK -lvtkIO -lvtkRendering -lvtkCommon -L/usr/lib/vtk-5.0/ -lqt-mt -lXext -lX11 -lm -lpthread
AR       = ar cqs
RANLIB   = 
MOC      = /usr/share/qt3/bin/moc
UIC      = /usr/share/qt3/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = src/flowfield.h \
		src/qtripp.h \
		src/vtk.h
SOURCES = src/flowfield.cpp \
		src/main.cpp \
		src/qtripp.cpp \
		src/vtk.cpp
OBJECTS = flowfield.o \
		main.o \
		qtripp.o \
		vtk.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = src/moc_flowfield.cpp \
		src/moc_qtripp.cpp \
		src/moc_vtk.cpp
OBJMOC = moc_flowfield.o \
		moc_qtripp.o \
		moc_vtk.o
DIST	   = qtRipp.pro
QMAKE_TARGET = Lattice_Boltzmann
DESTDIR  = bin/
TARGET   = bin/Lattice_Boltzmann

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: qtRipp.pro  /usr/share/qt3/mkspecs/default/qmake.conf /usr/share/qt3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile qtRipp.pro
qmake: 
	@$(QMAKE) -o Makefile qtRipp.pro

dist: 
	@mkdir -p .tmp/Lattice_Boltzmann && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/Lattice_Boltzmann/ && ( cd `dirname .tmp/Lattice_Boltzmann` && $(TAR) Lattice_Boltzmann.tar Lattice_Boltzmann && $(GZIP) Lattice_Boltzmann.tar ) && $(MOVE) `dirname .tmp/Lattice_Boltzmann`/Lattice_Boltzmann.tar.gz . && $(DEL_FILE) -r .tmp/Lattice_Boltzmann

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:

yaccclean:
lexclean:
clean: mocclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) bin/$(TARGET) $(TARGET)


FORCE:

####### Compile

flowfield.o: src/flowfield.cpp src/flowfield.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o flowfield.o src/flowfield.cpp

main.o: src/main.cpp src/qtripp.h \
		src/vtk.h \
		src/flowfield.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

qtripp.o: src/qtripp.cpp src/qtripp.h \
		src/vtk.h \
		src/flowfield.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtripp.o src/qtripp.cpp

vtk.o: src/vtk.cpp src/vtk.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vtk.o src/vtk.cpp

moc_flowfield.o: src/moc_flowfield.cpp  src/flowfield.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_flowfield.o src/moc_flowfield.cpp

moc_qtripp.o: src/moc_qtripp.cpp  src/qtripp.h src/vtk.h \
		src/flowfield.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtripp.o src/moc_qtripp.cpp

moc_vtk.o: src/moc_vtk.cpp  src/vtk.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_vtk.o src/moc_vtk.cpp

src/moc_flowfield.cpp: $(MOC) src/flowfield.h
	$(MOC) src/flowfield.h -o src/moc_flowfield.cpp

src/moc_qtripp.cpp: $(MOC) src/qtripp.h
	$(MOC) src/qtripp.h -o src/moc_qtripp.cpp

src/moc_vtk.cpp: $(MOC) src/vtk.h
	$(MOC) src/vtk.h -o src/moc_vtk.cpp

####### Install

install:  

uninstall:  

